=== Crazy2286855675/shadcn-ui/apps/www/public/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "style": {
      "type": "string",
      "enum": ["default", "new-york"]
    },
    "tailwind": {
      "type": "object",
      "properties": {
        "config": {
          "type": "string"
        },
        "css": {
          "type": "string"
        },
        "baseColor": {
          "type": "string"
        },
        "cssVariables": {
          "type": "boolean"
        }
      },
      "required": ["config", "css", "baseColor", "cssVariables"]
    },
    "rsc": {
      "type": "boolean"
    },
    "aliases": {
      "type": "object",
      "properties": {
        "utils": {
          "type": "string"
        },
        "components": {
          "type": "string"
        }
      },
      "required": ["utils", "components"]
    },
    "components": {
      "type": "object",
      "properties": {
        "capitalizedFilenames": {
          "type": "boolean",
          "default": false,
          "description": "Allow filenames of components start with an uppercase letter."
        }
      }
    }
  },
  "required": ["style", "tailwind", "rsc", "aliases"]
}

=== Crazy2286855675/shadcn-ui/templates/next-template/components.json
{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "default",
  "tailwind": {
    "rtl": true,
    "config": "tailwind.config.js",
    "css": "app/globals.css",
    "baseColor": "slate",
    "cssVariables": true
  },
  "rsc": false,
  "aliases": {
    "utils": "@/lib/utils",
    "components": "@/components"
  }
}
